Repository pyjanitor-devs/pyjanitor, pull requests merged in 2019-07, with the labels that each got.

#411 [DOC] added spaces between Example2 and Example3
  AUTHORS.rst
  examples/add_column.md
Labels: being worked on, docfix, good first issue

#413 [DOC] Backtick doc fix #401 WIP
  AUTHORS.rst
  examples/notebooks/bad_values.ipynb
  examples/notebooks/board_games.ipynb
  examples/notebooks/dirty_data.ipynb
  examples/notebooks/normalize.ipynb
  examples/notebooks/pyjanitor_intro.ipynb
  janitor/biology.py
  janitor/chemistry.py
  janitor/finance.py
  janitor/functions.py
  janitor/utils.py
  tests/biology/test_join_fasta.py
  tests/finance/test_convert_currency.py
  tests/functions/test_join_apply.py
  tests/utils/test_clean_accounting_column.py
  tests/utils/test_currency_column_to_numeric.py
  tests/utils/test_import_message.py
  tests/utils/test_replace_empty_string_with_none.py
Labels: docfix, good first issue

#437 [DOC] Authors template
  AUTHORS.rst
Labels: docfix
